### ISSUE TITLE
interal server error 500 am not sure how to fix this

### ISSUE THREAD

**Issue by Mr-hackerman** [0ssamaak0/SiriLLama#2]
* Serving Flask app 'app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.50.15:5000
Press CTRL+C to quit
[2024-05-30 15:30:35,019] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Downloads\SiriLLama-main\SiriLLama-main\app.py", line 175, in generate_route
    response = generate(prompt)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Downloads\SiriLLama-main\SiriLLama-main\app.py", line 145, in generate
    response = main_chain2.invoke({"input": user_input})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_core\runnables\base.py", line 2399, in invoke
    input = step.invoke(
            ^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_core\prompts\base.py", line 128, in invoke
    return self._call_with_config(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_core\runnables\base.py", line 1509, in _call_with_config
    context.run(
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_core\runnables\config.py", line 346, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_core\prompts\base.py", line 111, in _format_prompt_with_error_handling
    _inner_input = self._validate_input(inner_input)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_core\prompts\base.py", line 103, in _validate_input
    raise KeyError(
KeyError: "Input to ChatPromptTemplate is missing variables {'ANSWER_SIZE_WORDS'}.  Expected: ['ANSWER_SIZE_WORDS', 'history', 'input'] Received: ['input', 'history']"
192.168.50.73 - - [30/May/2024 15:30:35] "POST / HTTP/1.1" 500 -

**Comment by 0ssamaak0** [comment]
Have u make any changes in app.py?

**Comment by 0ssamaak0** [comment]
Did u make any changes in app.py?

**Comment by Mr-hackerman** [comment]
No I didn't change anything in it. Just left it as it is. Although my Ollama instance runs with a different configuration instead of 127.0.0.1 it runs on 192.168.50.15. Do I need to change that in app.py.

**Comment by 0ssamaak0** [comment]
- 127.0.0.1 is how your machine addresses itself. Don't use it in Shortcuts or anywhere else

- when you open the shortcut for 
the first time, you get a panel to enter your IP. Enter 192.168.... in it. Or enter it manually like this: ![image](https://github.com/0ssamaak0/SiriLLama/assets/53372259/c7ba9154-c0bf-47a8-b47b-35de0cce964a)

It should work now 😃

**Comment by Mr-hackerman** [comment]
Yup fixed it thank you for your effort and time.
